[tox]
envlist =
    py38
    py39
    py310
    #py311
    coverage
    lint

[gh-actions]
python =
    3.8: py38, coverage
    3.9: py39, coverage
    3.10: py310, coverage
    #3.11: py311, coverage

[testenv]
deps =
    aioresponses
    coverage
    pytest
    pytest-aioresponses
    pytest-aiohttp
    python-dateutil
    pyee
    ../../api/python
commands = 
    coverage run --source crosslab.soa_client -m pytest -W error

[testenv:coverage]
basepython =
    python3
skip_install =
    true
deps =
    coverage
commands =
    coverage combine
    coverage report
    coverage xml
depends =
    py38
    py39

[testenv:lint]
basepython =
    python3
deps =
    aioresponses
    flake8
    mypy
    types-python-dateutil
    ../../api/python
commands =
    flake8 src
    mypy --check-untyped-defs src

[coverage:run]
parallel=True

[coverage:paths]
source =
    src/crosslab/soa_client
    .tox/*/lib/python*/site-packages/crosslab/soa_client

[flake8]
max_line_length = 120
per-file-ignores =
    src/crosslab/soa_client/schemas.py:E501,E722,E201,E202,W292
#    src/crosslab_api_client/client.py:F405,W293,F811 # F811: postDeviceToken redifinition
#    src/crosslab_api_client/__init__.py:F401